require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec


inherit_mode:
  merge:
    - Exclude

AllCops:
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 7

RSpec/NestedGroups:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false # TODO: enable this?
