language: ruby
# Ruby versions to run tests on.
# We will not test on Ruby versions thar are no longer supported (EOL).
# List of Ruby releases: https://www.ruby-lang.org/en/downloads/releases/
# Maintenance status of each Ruby series https://www.ruby-lang.org/en/downloads/branches/
rvm:
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - ruby-head
# Rails versions to run tests on.
# We will not test on Rails versions thar are no longer supported (EOL).
# List of Rails releases: https://rubygems.org/gems/rails/versions
# Maintenance status of each Rails series: https://guides.rubyonrails.org/maintenance_policy.html
gemfile:
  - Gemfile # it should use latest public rails version
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
  - gemfiles/railsmaster.gemfile
matrix:
  # When testing against the head or master (unreleased versions) of Ruby or
  # Rails, failures may occur because the branch is unstable and not due to our
  # project. For these cases, we'll allow failures until official versions are
  # released.
  allow_failures:
    - gemfile: gemfiles/railsmaster.gemfile
    - rvm: ruby-head
  # Some Rails versions do not work with older Ruby versions.
  exclude:
# See https://docs.travis-ci.com/user/caching/#bundler
cache: bundler
sudo: false
before_install:
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email: false
