language: ruby
# Ruby versions to run tests on.
# We will not test on Ruby versions thar are no longer supported (EOL).
# List of Ruby releases: https://www.ruby-lang.org/en/downloads/releases/
# Maintenance status of each Ruby series https://www.ruby-lang.org/en/downloads/branches/
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - ruby-head
# Rails versions to run tests on.
# We will not test on Rails versions thar are no longer supported (EOL).
# List of Rails releases: https://rubygems.org/gems/rails/versions
# Maintenance status of each Rails series: https://guides.rubyonrails.org/maintenance_policy.html
gemfile:
  - Gemfile
  - gemfiles/rails40.gemfile # If we say the gem supports Rails >= 4, it should be tested with 4.0.0 as well.
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
  - gemfiles/railsmaster.gemfile
matrix:
  # When testing against the head or master (unreleased versions) of Ruby or
  # Rails, failures may occur because the branch is unstable and not due to our
  # project. For these cases, we'll allow failures until official versions are
  # released.
  allow_failures:
    - gemfile: gemfiles/railsmaster.gemfile
    - rvm: ruby-head
  # Some Rails versions do not work with older Ruby versions.
  exclude:
    # Rails >= 6 requires Ruby version >= 2.5.0
    - rvm: 2.4.10
      gemfile: Gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/railsmaster.gemfile
    # sqlite3-1.3.13/lib/sqlite3/sqlite3_native.so: undefined symbol: rb_check_safe_obj
    - rvm: ruby-head
      gemfile: gemfiles/rails5.gemfile
    # I was unable to get Ruby head to work with Bundler < 2, which is required by Rails ~> 4
    - rvm: 2.7.2
      gemfile: gemfiles/rails4.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails4.gemfile
    # Rails 4.0.0 only works with Ruby 2.3.8
    - rvm: 2.4.10
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.5.8
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/rails40.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails40.gemfile
# See https://docs.travis-ci.com/user/caching/#bundler
cache: bundler
sudo: false
before_install:
  # Rails ~> 4.2.x does not work with Bundle 2.0. The gem uninstall command
  # removes any Bundler 2.x installed in RVM’s “global” gemset during the Ruby run
  # time installation, which would be selected as the default bundle command. We
  # ignore the failure from that command, because the failure most likely means
  # that there was no matching Bundler version to uninstall.
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2' --no-document
script:
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email: false
